import '../../modelos/materia.dart';

const String kHistoriaPlanPdfUrl =
    'https://drive.google.com/file/d/13znCaPZBl00OHVRLZhJ6Fh8CQaGIKi63/view?usp=sharing';

Materia _materia({
  required String id,
  required String codigo,
  required String nombre,
  required int anio,
  required String tipo,
  required String formato,
  String? horas,
  int? cuatri,
}) {
  return Materia(
    id: id,
    codigo: codigo,
    nombre: nombre,
    anio: anio,
    cuatri: cuatri,
    tipo: tipo,
    formato: formato,
    horas: horas,
    correlativas: const [],
    correlativasDetalladas: const [],
  );
}

List<Materia> buildHistoriaCatalogMaterias() {
  return [
    _materia(
      id: 'pedagogia',
      codigo: 'PED',
      nombre: 'Pedagog\u00eda',
      anio: 1,
      tipo: 'Formaci\u00f3n General',
      formato: 'Asignatura',
      horas: '4 hs',
    ),
    _materia(
      id: 'problematica-conocimiento',
      codigo: 'PCH',
      nombre: 'Problem\u00e1tica del Conocimiento Hist\u00f3rico',
      anio: 1,
      tipo: 'Formaci\u00f3n Espec\u00edfica',
      formato: 'Asignatura',
      horas: '4 hs',
    ),
    _materia(
      id: 'procesos-antiguedad',
      codigo: 'ANT',
      nombre:
          'Procesos Sociales, Pol\u00edticos, Econ\u00f3micos y Culturales de la Antig\u00fcedad',
      anio: 1,
      tipo: 'Formaci\u00f3n Espec\u00edfica',
      formato: 'Asignatura',
      horas: '5 hs',
    ),
    _materia(
      id: 'historia-ideas-1',
      codigo: 'HI1',
      nombre: 'Historia de las Ideas I',
      anio: 1,
      tipo: 'Formaci\u00f3n Espec\u00edfica',
      formato: 'Seminario',
      horas: '3 hs',
    ),
    _materia(
      id: 'pueblos-originarios',
      codigo: 'POA',
      nombre:
          'Procesos Sociales, Pol\u00edticos, Econ\u00f3micos y Culturales de los Pueblos Originarios de Am\u00e9rica',
      anio: 1,
      tipo: 'Formaci\u00f3n Espec\u00edfica',
      formato: 'Asignatura',
      horas: '4 hs',
    ),
    _materia(
      id: 'oralidad-lectura',
      codigo: 'OLT',
      nombre: 'Oralidad, Lectura, Escritura y TIC',
      anio: 1,
      tipo: 'Formaci\u00f3n General',
      formato: 'Taller',
      horas: '3 hs',
    ),
    _materia(
      id: 'corporeidad-juego',
      codigo: 'CJA',
      nombre: 'Corporeidad, Juego y Lenguajes Art\u00edsticos',
      anio: 1,
      tipo: 'Formaci\u00f3n General',
      formato: 'Taller',
      horas: '3 hs',
    ),
    _materia(
      id: 'practica-1',
      codigo: 'PD1',
      nombre: 'Pr\u00e1ctica Docente I - Sujetos y Contextos',
      anio: 1,
      tipo: 'Pr\u00e1ctica Profesional',
      formato: 'Seminario-Taller',
      horas: '4 hs',
    ),
    _materia(
      id: 'didactica-general',
      codigo: 'DG',
      nombre: 'Did\u00e1ctica General',
      anio: 1,
      tipo: 'Formaci\u00f3n General',
      formato: 'Asignatura',
      horas: '4 hs',
    ),
    _materia(
      id: 'filosofia',
      codigo: 'FIL',
      nombre: 'Filosof\u00eda',
      anio: 2,
      tipo: 'Formaci\u00f3n General',
      formato: 'Asignatura',
      horas: '3 hs',
    ),
    _materia(
      id: 'psicologia-educacional',
      codigo: 'PE',
      nombre: 'Psicolog\u00eda Educacional',
      anio: 2,
      tipo: 'Formaci\u00f3n General',
      formato: 'Asignatura',
      horas: '4 hs',
    ),
    _materia(
      id: 'educacion-sexual',
      codigo: 'ESI',
      nombre: 'Educaci\u00f3n Sexual Integral',
      anio: 2,
      tipo: 'Formaci\u00f3n General',
      formato: 'Taller',
      horas: '2 hs',
    ),
    _materia(
      id: 'procesos-feudalismo-modernidad',
      codigo: 'FM',
      nombre:
          'Procesos Sociales, Pol\u00edticos, Econ\u00f3micos y Culturales del Feudalismo y la Modernidad',
      anio: 2,
      tipo: 'Formaci\u00f3n Espec\u00edfica',
      formato: 'Asignatura',
      horas: '4 hs',
    ),
    _materia(
      id: 'procesos-americanos-1',
      codigo: 'AM1',
      nombre:
          'Procesos Sociales, Pol\u00edticos, Econ\u00f3micos y Culturales Americanos I',
      anio: 2,
      tipo: 'Formaci\u00f3n Espec\u00edfica',
      formato: 'Asignatura',
      horas: '3 hs',
    ),
    _materia(
      id: 'historia-ideas-2',
      codigo: 'HI2',
      nombre: 'Historia de las Ideas II',
      anio: 2,
      tipo: 'Formaci\u00f3n Espec\u00edfica',
      formato: 'Seminario',
      horas: '3 hs',
    ),
    _materia(
      id: 'mundo-territorialidades',
      codigo: 'MT',
      nombre: 'El Mundo y las Nuevas Territorialidades',
      anio: 2,
      tipo: 'Formaci\u00f3n Espec\u00edfica',
      formato: 'Asignatura',
      horas: '3 hs',
    ),
    _materia(
      id: 'economia-politica',
      codigo: 'EP',
      nombre: 'Econom\u00eda Pol\u00edtica',
      anio: 2,
      tipo: 'Formaci\u00f3n Espec\u00edfica',
      formato: 'Seminario',
      horas: '3 hs',
    ),
    _materia(
      id: 'didactica-ciencias-sociales',
      codigo: 'DCS',
      nombre: 'Did\u00e1ctica de las Ciencias Sociales',
      anio: 2,
      tipo: 'Formaci\u00f3n Espec\u00edfica',
      formato: 'Seminario',
      horas: '3 hs',
    ),
    _materia(
      id: 'sujetos-educacion',
      codigo: 'SE',
      nombre: 'Sujetos de la Educaci\u00f3n Secundaria',
      anio: 2,
      tipo: 'Formaci\u00f3n General',
      formato: 'Seminario',
      horas: '3 hs',
    ),
    _materia(
      id: 'practica-2',
      codigo: 'PD2',
      nombre:
          'Pr\u00e1ctica Docente II - Educaci\u00f3n Secundaria y Pr\u00e1ctica Docente',
      anio: 2,
      tipo: 'Pr\u00e1ctica Profesional',
      formato: 'Seminario-Taller',
      horas: '4 hs',
    ),
    _materia(
      id: 'historia-politica-educacion',
      codigo: 'HPE',
      nombre: 'Historia y Pol\u00edtica de la Educaci\u00f3n Argentina',
      anio: 3,
      tipo: 'Formaci\u00f3n General',
      formato: 'Asignatura',
      horas: '3 hs',
    ),
    _materia(
      id: 'sociologia-educacion',
      codigo: 'SOE',
      nombre: 'Sociolog\u00eda de la Educaci\u00f3n',
      anio: 3,
      tipo: 'Formaci\u00f3n General',
      formato: 'Asignatura',
      horas: '3 hs',
    ),
    _materia(
      id: 'instituciones-educativas',
      codigo: 'IE',
      nombre:
          'An\u00e1lisis y Organizaci\u00f3n de las Instituciones Educativas',
      anio: 3,
      tipo: 'Formaci\u00f3n General',
      formato: 'Asignatura',
      horas: '3 hs',
    ),
    _materia(
      id: 'procesos-contemporaneos-1',
      codigo: 'C1',
      nombre:
          'Procesos Sociales, Pol\u00edticos, Econ\u00f3micos y Culturales Contempor\u00e1neos I',
      anio: 3,
      tipo: 'Formaci\u00f3n Espec\u00edfica',
      formato: 'Asignatura',
      horas: '3 hs',
    ),
    _materia(
      id: 'procesos-americanos-2',
      codigo: 'AM2',
      nombre:
          'Procesos Sociales, Pol\u00edticos, Econ\u00f3micos y Culturales Americanos II',
      anio: 3,
      tipo: 'Formaci\u00f3n Espec\u00edfica',
      formato: 'Asignatura',
      horas: '3 hs',
    ),
    _materia(
      id: 'procesos-argentina-1',
      codigo: 'AR1',
      nombre:
          'Procesos Sociales, Pol\u00edticos, Econ\u00f3micos y Culturales de Argentina I',
      anio: 3,
      tipo: 'Formaci\u00f3n Espec\u00edfica',
      formato: 'Asignatura',
      horas: '4 hs',
    ),
    _materia(
      id: 'epistemologia-historia',
      codigo: 'EH',
      nombre: 'Epistemolog\u00eda de la Historia',
      anio: 3,
      tipo: 'Formaci\u00f3n Espec\u00edfica',
      formato: 'Seminario',
      horas: '3 hs',
    ),
    _materia(
      id: 'didactica-historia',
      codigo: 'DH',
      nombre: 'Did\u00e1ctica de la Historia',
      anio: 3,
      tipo: 'Formaci\u00f3n Espec\u00edfica',
      formato: 'Asignatura',
      horas: '3 hs',
    ),
    _materia(
      id: 'udi-1',
      codigo: 'UDI1',
      nombre: 'UDI I',
      anio: 3,
      tipo: 'Formaci\u00f3n Espec\u00edfica',
      formato: 'Variable',
      horas: '3 hs',
    ),
    _materia(
      id: 'practica-3',
      codigo: 'PD3',
      nombre: 'Pr\u00e1ctica Docente III - Cotidianeidad en las Aulas',
      anio: 3,
      tipo: 'Pr\u00e1ctica Profesional',
      formato: 'Seminario-Taller',
      horas: '6 hs',
    ),
    _materia(
      id: 'derechos-humanos',
      codigo: 'DHU',
      nombre: 'Derechos Humanos: \u00c9tica y Ciudadan\u00eda',
      anio: 4,
      tipo: 'Formaci\u00f3n General',
      formato: 'Asignatura',
      horas: '3 hs',
    ),
    _materia(
      id: 'procesos-contemporaneos-2',
      codigo: 'C2',
      nombre:
          'Procesos Sociales, Pol\u00edticos, Econ\u00f3micos y Culturales Contempor\u00e1neos II',
      anio: 4,
      tipo: 'Formaci\u00f3n Espec\u00edfica',
      formato: 'Asignatura',
      horas: '3 hs',
    ),
    _materia(
      id: 'procesos-americanos-3',
      codigo: 'AM3',
      nombre:
          'Procesos Sociales, Pol\u00edticos, Econ\u00f3micos y Culturales Americanos III',
      anio: 4,
      tipo: 'Formaci\u00f3n Espec\u00edfica',
      formato: 'Asignatura',
      horas: '4 hs',
    ),
    _materia(
      id: 'procesos-argentina-2',
      codigo: 'AR2',
      nombre:
          'Procesos Sociales, Pol\u00edticos, Econ\u00f3micos y Culturales de Argentina II',
      anio: 4,
      tipo: 'Formaci\u00f3n Espec\u00edfica',
      formato: 'Seminario-Taller',
      horas: '4 hs',
    ),
    _materia(
      id: 'problematicas-regionales',
      codigo: 'PR',
      nombre: 'Problem\u00e1ticas Hist\u00f3ricas Regionales y Locales',
      anio: 4,
      tipo: 'Formaci\u00f3n Espec\u00edfica',
      formato: 'Taller',
      horas: '4 hs',
    ),
    _materia(
      id: 'udi-2',
      codigo: 'UDI2',
      nombre: 'UDI II',
      anio: 4,
      tipo: 'Formaci\u00f3n Espec\u00edfica',
      formato: 'Variable',
      horas: '3 hs',
    ),
    _materia(
      id: 'practica-4',
      codigo: 'RES',
      nombre: 'Pr\u00e1ctica Docente IV - Residencia',
      anio: 4,
      tipo: 'Pr\u00e1ctica Profesional',
      formato: 'Seminario-Taller',
      horas: '10 hs',
    ),
  ];
}
